# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

executors:
  my-executor:
    docker:
      - image: buildpack-deps:jessie
    working_directory: /repo

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
      - run: mvn sonar:sonar -Dsonar.projectKey=AlissonMedeiros_assembly-line -Dsonar.organization=alissonmedeiros-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=5883a4b728fdff728a176c01d5b8375e9d37feab
      - persist_to_workspace:
          root: target/
          paths:
            - target/assembly-line.jar
  build-docker:
    environment:
      IMAGE_NAME: themedeiros/assembly-line
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo
    steps:
      - attach_workspace:
            # Must be absolute path or relative path from working_directory
            at: .
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            ll | docker build -t $IMAGE_NAME:latest . |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - build-docker:
          requires:
            - build
